### PR TITLE
fix 'Provided signature is invalid' error

### PR DESCRIPTION
**Pull request by eladeon**
Hi,

Here is the fix after the recent 3Commas API update today started causing various 'Provided signature is invalid' errors + some of my other changes in order to get this implementation working with various GET's and POST requests 

Regards

### CODE REVIEW

**Comment by bogdanteodoru** [comment]
@eladeon can you fix the conflict please? Afterwards I can safely merge it. Thanks.

**Comment by eladeon** [comment]
Hi Bogdan, sorry for the delay: have resolved the merge conflict. That said, I did back out the changes from master since my changes contained a similar fix (although implemented slightly differently): I've created a new branch on my forked repo with this "provided_signature_is_invalid_fix": Not sure how you feel about this - but it does resolve the "provided_signature_is_invalid" issue

**Comment by bogdanteodoru** [comment]
@eladeon I took the changes manually because it was easier than fixing the conflicts. I thanked you in the commit message :) Thanks here as well. I will close this.

**Comment by eladeon** [comment]
my pleasure ;) and thanks for the library! very useful to get started quickly on 3commas!

**Pull request closed without merging**
